### ISSUE TITLE
Not finding Window AC (LG LW1517IVSM)

### ISSUE THREAD

**Issue by sbukiet** [fison67/LG-Connector#7]
I've gone through all the steps but docker isn't finding/adding my Window AC. Supported devices shows Air Conditioners, is there something I need to do to get this working?

**Comment by Giltechy** [comment]
Even I am facing same problem

**Comment by sbukiet** [comment]
@fison67 Any advice for us?

**Comment by fison67** [comment]
If you can't find a device, it's a connected with new server(v2).
Use a fison67/lg-connector:beta or -rasp:beta image.
Then set a token on settinga page. Maybe you can find a AC.
But it's available on monitoring, can't control a device yet.

**Comment by Giltechy** [comment]
@fison67  this is perfect, able to find my washers in dashboard and added in smartthings except my dishwasher(no dth). In smartthings its not fetching data from LG, so the values in smartthings are null.

thanks for this, waiting for your full release.

**Comment by fison67** [comment]
@Giltechy When you turn on & off a washer, no logs?

**Comment by Giltechy** [comment]
@fison67  no the washer is not registering in the logs

![image](https://user-images.githubusercontent.com/40049841/85380305-68e8e900-b55a-11ea-8a74-9eb8ba70ea16.png)

**Comment by fison67** [comment]
@Giltechy 
There is no mqtt logs as below?
![image](https://user-images.githubusercontent.com/2555973/85513388-eb92a680-b635-11ea-809c-323530cf0081.png)

**Comment by Giltechy** [comment]
@fison67  thanks for your support

getting this error in mqtt 
2020-06-24 17:24:00	error	(node:28) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2020-06-24 17:24:00	error	(node:28) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
2020-06-24 17:24:00	error	(node:28) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'match' of undefined at normalize (/usr/src/app/node_modules/url-join/lib/url-join.js:11:21) at /usr/src/app/node_modules/url-join/lib/url-join.js:70:12 at Finder.refresh_auth (/usr/src/app/service/smartthinq/v1/finder.js:394:21) at Finder.setPrivateData (/usr/src/app/service/smartthinq/v1/finder.js:295:17) at LGDeviceManager._initSmartthinq (/usr/src/app/service/manager.js:112:29) at Timeout._onTimeout (/usr/src/app/service/manager.js:105:18) at listOnTimeout (internal/timers.js:549:17) at processTimers (internal/timers.js:492:7)
2020-06-24 17:23:58	info	TypeError: Cannot read property 'privateKey' of undefined at FinderV2.connectMQTT (/usr/src/app/service/smartthinq/v2/base.js:72:19) at FinderV2.initMQTT (/usr/src/app/service/smartthinq/v2/finder.js:50:10) at /usr/src/app/service/smartthinq/v2/finder.js:27:12

**Comment by fison67** [comment]
Try to a get token again.
Then let me know your logs.

**Comment by Giltechy** [comment]
@fison67 

Logs after token refresh 



2020-06-25 15:14:12 | info | Set ST App Info from a GH-Connector Smartapp
2020-06-25 15:14:12 | info | Save Config >> {"system":{"mode":"Auto","address":"10.0.x.xx","port":"30020"},"user":{"name":"admin","password":"12345"},"st":{"app_url":"https://graph-ap02-apnortheast2.api.smartthings.com:443/api/smartapps/installations/","app_id":"92c06f1x-c100-4339-8f97-xxxxxxxxxxx","access_token":"d9a4055e-4522-41ee-bc29-xxxxxxxxx"},"smartthinq":{"refresh_token":"","auth_base":"","api_root":"","oauth_root":""},"token":"17383e05f099c207aaed103374634460e7f057e1a6f42cb7c527cec757fb9e5711d8c7eafcd169925b63270xxxxxx","devices":{"list":[]},"preset":{"country":"US","language":"en-US"},"pollingTime":1}
2020-06-25 15:13:32 | info | Success to register device Address(44:cb:8b:1f:xx:xx)
2020-06-25 15:13:22 | info | Success to register device Address(44:cb:8b:63:xx:xx)




2020-06-25 15:13:20 | error | (node:28) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
-- | -- | --
2020-06-25 15:13:20 | error | (node:28) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
2020-06-25 15:13:20 | error | (node:28) UnhandledPromiseRejectionWarning: Error: Request failed with status code 400 at createError (/usr/src/app/node_modules/axios/lib/core/createError.js:16:15) at settle (/usr/src/app/node_modules/axios/lib/core/settle.js:17:12) at IncomingMessage.handleStreamEnd (/usr/src/app/node_modules/axios/lib/adapters/http.js:236:11) at IncomingMessage.emit (events.js:327:22) at endReadableNT (_stream_readable.js:1221:12) at processTicksAndRejections (internal/process/task_queues.js:84:21)
2020-06-25 15:13:17 | info | Find V2 >> Laundry [44:cb:8b:1f:xx:XX]
2020-06-25 15:13:16 | info | Find V2 >> Washer [44:cb:8b:63:xx:XX]
2020-06-25 15:13:15 | info | processRegisterKey: 2c5c7b457906e208934360a66aa8aab3a080x4db304c3259e08c38d32880b17a, 39ab61c0a28cb3a8608c0ce851914a9b75fd312d3b72716d4f5f38a7343bc2942841d920f68f55cca0b4814c4c90xxxx, dtCookie=EA506269B06099CFC0882A18D5D54xxx;domain=lgthinq.com;path=/
2020-06-25 15:12:03 | error | (node:28) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
2020-06-25 15:12:03 | info | [ TV ] Scanning... If your TV is off, turn on now.

**Comment by teslamine** [comment]
I am getting the same thing on my end:


```
TypeError: Cannot read property 'privateKey' of undefined at FinderV2.connectMQTT (/usr/src/app/service/smartthinq/v2/base.js:73:19) at FinderV2.initMQTT (/usr/src/app/service/smartthinq/v2/finder.js:50:10) at /usr/src/app/service/smartthinq/v2/finder.js:27:12
--

```

**Comment by fison67** [comment]
@Giltechy 
I didn't test by other country account.
I'm gonna test  with  US account soon.

**Comment by Giltechy** [comment]
@fison67  thanks for the response, waiting for your build. let me know for any testing required.

**Comment by fison67** [comment]
@Giltechy 
Re download a docker image (beta).

**Comment by teslamine** [comment]
`

2020-07-06 11:59:39 | info | Find V2 >> Washer [60:ab:14:73:4d:be]
-- | -- | --
2020-07-06 11:59:38 | info | Find V2 >> Dryer [60:ab:14:4c:6a:50]
2020-07-06 11:59:37 | error | (node:29) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
2020-07-06 11:59:37 | info | [ TV ] Scanning... If your TV is off, turn on now.
2020-07-06 11:59:37 | info | TV Scan....
2020-07-06 11:59:37 | info | Iitialize TV Devices....
2020-07-06 11:59:36 | info | Access Token is updated from xxx to xxx
2020-07-06 11:59:34 | info | Request to update a access token by refresh token.
2020-07-06 11:59:33 | info | TypeError: Cannot read property 'privateKey' of undefined at FinderV2.connectMQTT (/usr/src/app/service/smartthinq/v2/base.js:73:19) at FinderV2.initMQTT (/usr/src/app/service/smartthinq/v2/finder.js:50:10) at /usr/src/app/service/smartthinq/v2/finder.js:27:12
2020-07-06 11:59:33 | info | Polling Time: 1Mins
2020-07-06 11:59:33 | info | {"system":{"mode":"Auto","address":"xxx","port":"xxx"},"user":{"name":"admin","password":"xxx"},"st":{"app_url":"https://graph-na02-useast1.api.smartthings.com:443/api/smartapps/installations/","app_id":"xxx","access_token":"xxx"},"smartthinq":{"refresh_token":""},"token":"xxx","devices":{"list":[]},"preset":{"country":"US","language":"en-US"},"pollingTime":1}
2020-07-06 11:59:33 | info | WebSocket init

`

**Comment by fison67** [comment]
@teslamine
RE get token on setting page.

**Comment by teslamine** [comment]
@fison67 

mqtt connected successfully. there are still some errors. please see below. Also - on smartthings app, the washer/dryer doesn't show any status or data. just blank. 

`

2020-07-06 13:18:51 | info | {"data":{"state":{"reported":{"meta":{"allDeviceInfoUpdate":false,"messageId":"lwZ39-rfSVK9HdrylKv1fw"},"mid":19875511,"online":true,"static":{"countryCode":"US","deviceType":"202"},"timestamp":1594009131823,"washerDryer":{"remainTimeMinute":21}}}},"deviceId":"de8eea56-086e-19a9-b865-60ab144c6a50","type":"monitoring"}
-- | -- | --
2020-07-06 13:17:52 | info | {"data":{"state":{"reported":{"meta":{"allDeviceInfoUpdate":false,"messageId":"Zj5TScL6QzmyYiK7eQG2xw"},"mid":19814162,"online":true,"static":{"countryCode":"US","deviceType":"202"},"timestamp":1594009071934,"washerDryer":{"remainTimeMinute":22}}}},"deviceId":"de8eea56-086e-19a9-b865-60ab144c6a50","type":"monitoring"}
2020-07-06 13:17:45 | error | (node:28) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
2020-07-06 13:17:45 | info | [ TV ] Scanning... If your TV is off, turn on now.
2020-07-06 13:17:45 | info | TV Scan....
2020-07-06 13:17:45 | info | Iitialize TV Devices....
2020-07-06 13:17:44 | info | Find V2 >> Washer [60:ab:14:73:4d:be]
2020-07-06 13:17:44 | info | Find V2 >> Dryer [60:ab:14:4c:6a:50]
2020-07-06 13:17:44 | error | (node:28) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2020-07-06 13:17:44 | error | (node:28) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
2020-07-06 13:17:44 | error | (node:28) UnhandledPromiseRejectionWarning: #<Object>
2020-07-06 13:17:42 | info | Success to connect a MQTT Server.
2020-07-06 13:17:41 | info | Request to connect MQTT
2020-07-06 13:17:41 | info | Polling Time: 1Mins
2020-07-06 13:17:41 | info | {"system":{"mode":"Auto","address":"192.168.2.18","port":"30020"},"user":{"name":"admin","password":"lucky18"},"st":{"app_url":"https://graph-na02-useast1.api.smartthings.com:443/api/smartapps/installations/","app_id":"43d37928-bfe4-456c-8b31-677e5f6f4de8","access_token":"51c1c0e6-ab09-4c53-b810-6e895f436866"},"smartthinq":{"refresh_token":"6278439b669dc7d1c70a2ebfd1a45a54fd2436989995b907b373f09efda0f79a597044c9bcc804acb6907f986a28a750","auth_base":"https://us.m.lgaccount.com","api_root":"https://aic.lgthinq.com:46030/api","oauth_root":"https://us.lgeapi.com"},"token":"803ffceef3a9950deac879ff8c66575a89b2dcdba579be31ae98877208aa87bdd3ed659ad3e98a49a98ddf0954371e71","devices":{"list":[]},"preset":{"country":"US","language":"en-US"},"pollingTime":1}
2020-07-06 13:17:41 | info | WebSocket init

`

**Comment by fison67** [comment]
@teslamine 
Ignore some error .
It looks like a normal.
Check a logs on smartthings ide.

**Comment by teslamine** [comment]
@fison67 
Looks like dryer is getting some events now. I have to test again but "process" is coming through in Korean even though set to EN.

> 

LG Dryer v2 process state is 종료
--

**Comment by fison67** [comment]
@teslamine 
Update a dth, then try again.
When dryer status is changed, value will be set by english.

**Comment by Giltechy** [comment]
@fison67  Thanks for your code readiness in short time, now the washer added , only the processstate showing in korean, i have updated the DTH and run washer for multiple times, still the same

![image](https://user-images.githubusercontent.com/40049841/86595065-c860e300-bfb5-11ea-9326-1e7ae76f22bf.png)

![image](https://user-images.githubusercontent.com/40049841/86595076-cc8d0080-bfb5-11ea-8a37-ca72d21598d3.png)

**Comment by fison67** [comment]
@Giltechy 
Update a dth again.

**Comment by Giltechy** [comment]
@fison67  today i have updated the DTH, now i have zero changes to be published, still the process state in korean.

![image](https://user-images.githubusercontent.com/40049841/86711196-59c56900-c039-11ea-9205-80ebd053dad5.png)

![image](https://user-images.githubusercontent.com/40049841/86711409-8b3e3480-c039-11ea-914f-8b3571c8c28f.png)

**Comment by Giltechy** [comment]
@fison67  some how in the DTH its going to else part , i just changed the korean to english for me in DTH 

![image](https://user-images.githubusercontent.com/40049841/86741016-b4b88980-c054-11ea-94b3-291dfcbb1540.png)

**Comment by fison67** [comment]
@Giltechy 
I have no idea why don't show..
Just copy & paste washer v2 DTH.

**Comment by Giltechy** [comment]
@fison no luck with manual DTH configuration, any how no issues now.

**Comment by fison67** [comment]
@sbukiet
Update a smartapp & DTH, then restart a docker.

**Comment by sbukiet** [comment]
@fison67 

Thank you, I see the two AC's show up in the Home>Dashboard section. But they are not there under the "Devices" section or are they adding to my ST (I've updated both the DTH and SmartApps). Is there something I need to o to get them added?

Additionally when I use eth v2 Token it takes me to the https://KR.m.lgaccount.com/ vs the https://US.m.lgaccount.com/ even though I have the Country=US and Language=en-US.

Let me know if you want to see any logs or anything I can provide.

**Comment by sbukiet** [comment]
Was able to get the units added to my ST dashboard but temperature is showing in Celsius. How to I chnage to Fahrenheit? Also, when I turn the AC's off device doesn't update in ST (still shows as "ON")
